# AGENT_GUIDE.md — read this before editing this codebase

This file exists because two real, ship-blocking bugs already happened in this project from patterns that look reasonable in isolation. Read the landmine log (§2) before touching any of the listed files. When you fix a bug or make an architectural decision, add to this file in the SAME change — it is not optional, see §3.

## 1. Which doc to read for which area

| If you're changing... | Read first | Also update if behavior changes |
|---|---|---|
| Persona / system prompt / tutor voice | `docs/TUTOR_PERSONA.md`, `docs/ARCHITECTURE.md §7` | `docs/TUTOR_PERSONA.md`, this file's landmine log if you hit a new gotcha |
| Learner model, misconception logic, mastery/BKT, strategy profile | `docs/LEARNER_MODEL.md`, `docs/TEACHING_PLAN.md` | Same docs + `docs/TRACEABILITY.md` if it changes a tracked requirement |
| Any Gemini Live tool call (`src/live/liveConfig.ts` `ALL_TOOLS`) | `docs/ARCHITECTURE.md §6` | You MUST add a dispatch case in `server.ts`'s tool-call switch, or the tool silently no-ops with a generic `{result:'ok'}` ack and nothing persists — see landmine #2. |
| Data persistence / repo layer | `docs/ARCHITECTURE.md §4` | Change `src/adaptive/repo/file.ts` AND `src/adaptive/repo/firestore.ts` together — never one without the other. |
| REST routes / auth | `server/middleware/requireAuth.ts` first | `docs/ARCHITECTURE.md §5` |
| ParentPortal / any UI that caches per-(student, X) data | Landmine #1 below, first | — |
| Anything else / general layout | `docs/ARCHITECTURE.md` | — |
| Session-end Profiler / claims / claim validation | `docs/LEARNER_MODEL.md §5.2`, `src/adaptive/claimValidator.ts`'s header | Never let the Profiler (an LLM call) write confidence or bypass the validator — see the header comments in `profiler.ts`/`claimValidator.ts` and D-2026-09-26-6. |
| Any new Gemini text-generation call | `src/ai/gateway.ts`'s header first | Use `generateText`/`generateJSON` with a `role` — do NOT hand-roll another model-candidate-list-with-fallback (this exact duplication is why `gateway.ts` exists; see its header). |
| Product/strategy decisions (why X was chosen over Y) | `DECISIONS.md` (repo root) | Add a dated entry for any new architectural or product decision |
| Curriculum ingestion, course ids, board/grade/subject, admin upload | `docs/CURRICULUM.md`, then `src/curriculum/catalog.ts`'s and `structure.ts`'s headers | Keep all validation in `structure.ts` (no network) and all naming in `catalog.ts`; never build an id from a file name; never change a published concept's `id`, `conceptType` or misconception ids — learner history is keyed on them (landmine #6). Run `npm run test:curriculum`. |
| Anything served to a learner that a model generated (lesson text, quiz, board pictures, photos) — `src/quality/**`, `src/curriculum/{lessonGen,lessonPrompt,photoGen,serve}.ts` | `docs/CH1_FIX_PLAN.md`, `docs/BOARD_VISUALS.md`, landmines #15–#17 below | Every generated artefact goes through lints + critic and **fails closed** (withhold, never a generic fallback). Add a lint code to `src/quality/*` AND a fixture to `tests/smoke/quality.mjs`; run `npm run verify` |
| Overall build status vs spec | `docs/TRACEABILITY.md`, `PROJECT_STATE.md` | Update the relevant row/section |
| Text-channel tutor turn (`server/routes/tutor.ts`, `POST /api/tutor/turn`) | This file's landmine #8, `server/routes/tutor.ts`'s own header | `docs/TRACEABILITY.md` FR-25, `docs/TECHNICAL_SPEC.md` §4 if the request/response shape changes. Keep its tool declarations filtered from `src/live/liveConfig.ts`'s `ALL_TOOLS`, not a second hand-written copy — see D-2026-09-28-2. |
| Writing a new HTTP-based test that starts `server.ts` itself (not the offline `@google/genai`-stub style in `tests/run.mjs`) | Landmine #8 below, first | `package.json`'s `scripts` if you add a new `test:*` entry |
| Board pictures — what the Shape/3D views draw (`src/visual/**`, `BoardVisualView.tsx`, `Board3DView.tsx`), their generation, fact-checking, storage, or how the tutor reveals them | `docs/BOARD_VISUALS.md`, landmines #13–#14 | `docs/BOARD_VISUALS.md`; `docs/TUTOR_PERSONA.md` §7.1 if the tutor's use of them changes. Never add a per-topic renderer or give the model example pictures (`src/visual/samples.ts` is deliberately NOT in any prompt) — that re-creates the templates this system replaced. Run `npm run test:visuals` and look at `npm run preview:visuals -- --samples` after any renderer change: tests pass on markup that can still look wrong (see #14). |

## 2. Landmine log (append here every time you find or fix one — do not delete old entries)

### #1 — 2026-09-26 — Per-student UI state cached by a shared key, not a composite key
**File:** `src/components/ParentPortal.tsx`. **Symptom:** two students (Aisha, Marcus) sharing the same curriculum `conceptId` ("triangle congruence tests") — clicking "View evidence" on Marcus's card displayed Aisha's cached Q&A transcript, because `replayEvents`/`replayOpenFor`/`replayLoading` were all keyed by bare `conceptId`. **Fix:** key everything by `` `${studentId}::${conceptId}` `` via a `replayKey()` helper; also clear open-panel state on student switch.
**Generalized rule:** any client-side cache or open/expanded-state keyed by a concept, lesson, or item ID that is NOT globally unique per student must be composite-keyed with the student ID. Curriculum concept IDs in this app are shared across students by design (they're curriculum, not per-student) — never assume a "concept" key alone disambiguates a student.

### #2 — 2026-09-26 — A Gemini Live tool defined but never wired to a dispatch handler is a silent no-op
**Files:** `src/live/liveConfig.ts` (tool schema definition), `server.ts` (dispatch switch), `src/adaptive/learnerStore.ts` (persistence). **Symptom:** `record_confusion_signal` was a real tool the LLM could call (and the persona prompts it to call, e.g. when a child says "I don't understand" or disagrees with the tutor) — but `server.ts`'s dispatch fell through to the generic `sendToolResponse(call, { result: 'ok' })` ack for every tool except `assess_child_reasoning`. The LLM would say "I'll make a note of that," get told "ok" by the tool response, and nothing was ever saved anywhere. **Fix:** added `recordConfusionSignal()` in `learnerStore.ts` (writes to `AffectState.confusionSignals` tally + `ConceptState.notes`) and a real dispatch case in `server.ts`.
**Generalized rule:** defining a tool in `ALL_TOOLS` (`liveConfig.ts`) is necessary but NOT sufficient for it to do anything. Every tool name must have an explicit `if (call.name === '...')` branch in `server.ts`'s dispatch switch that calls a real persistence function, or it silently falls through to the generic ack — this fails silently (the LLM thinks it worked) and is easy to miss in a demo until someone specifically checks whether the data was saved. When adding a new tool, grep `server.ts` for the tool's name to confirm a non-generic handler exists before assuming it's live.

### #3 — 2026-09-26 — One high-confidence BKT observation could mark a concept "mastered" and auto-advance the curriculum
**Files:** `src/adaptive/bkt.ts` (`EVIDENCE_QUALITY`, `updateMastery`), `src/adaptive/ladder.ts` (`computeMasteryStatus` — already correct), `src/adaptive/learnerStore.ts:367` (`cs.masteryScore = bkt.masteryScore`, unguarded), `server.ts` (two auto-advance gates). **Symptom:** demo learner Priya's "Constructing and applying properties of perpendicular and angle bisectors" concept reportedly jumped from 0% to 99% mastery after a single short exchange. Hand-verified the math: at difficulty 1, `EVIDENCE_QUALITY.transferred.guessWeight = 0.10` makes pG collapse to ~0.02 on a virgin concept, so ONE `understandingDepth: 'transferred'` observation swings the BKT posterior from a 25% prior to ~96% (`pL=0.25, pS=0.03, pG=0.02 → posterior=0.9417 → pNext=0.9592`). `computeMasteryStatus()` already correctly requires `pKnown >= 0.80 AND >= 2 distinct ladder-level-3+ items` before calling a concept even "provisional" — but `cs.masteryScore` (the raw number shown in the UI and used for curriculum auto-advance) is set directly from the BKT posterior with none of that gating. Result: the numeric mastery bar and the categorical status can disagree (bar shows 99%, status would correctly say "none"), and worse, `server.ts`'s two auto-advance checks (`/api/session/start`, `/api/session/:sessionId/assess`) compared the raw, ungated `masteryScore >= 75` directly — so a single lucky/well-classified answer could genuinely advance a child past a concept, contradicting this project's own "should not move forward simply because the child produced a correct answer" principle.
**Fix applied (complete, 2026-09-26):** two layers, both required:
1. `server.ts`: added `isConceptMastered()`, used at both auto-advance call sites — requires the properly-gated `masteryStatus !== 'none'` when that field exists (the BKT/live-voice path, where the bug lived), falling back to the raw threshold only for the legacy `recordAttempt()` quiz-click path (which never sets `masteryStatus` and was not the reported failure mode — don't "fix" it the same way without first giving it its own status computation, or you'll break advancement there).
2. `src/adaptive/learnerStore.ts`'s `recordReasoningEvidence()`: shrinks the STORED `cs.masteryScore`/`cs.pKnown` to `MASTERY_THRESHOLD - 1` whenever `cs.masteryStatus === 'none'` but the raw posterior implied "mastered" — fixed AT THE SOURCE, not just at the advance gate or in the UI, because the raw ungated number also fed the tutor's own `/api/learner-context/*` prompt text and `src/plan/compile.ts`'s prerequisite-strength check (`pKnown < 0.6`), both of which could have let the tutor itself believe a child had mastered something from one answer. All downstream consumers (event log, `EvidenceEvent`, the live WS update, API responses, UI) now read this same one final number. See `docs/LEARNER_MODEL.md §6.1` for the full BKT-level explanation and why `EVIDENCE_QUALITY`'s guess/slip weights were deliberately left untouched (recalibrating them would be arbitrary tuning with no principled basis; reusing the existing evidence-sufficiency rule from `computeMasteryStatus` is not).
**Verified, not just asserted:** wrote and ran a standalone repro script bundling the real `learnerStore.ts` against a temp data dir — confirmed (a) one `transferred` observation on a virgin concept now stores 74%/`'none'` instead of 96%, and (b) two more genuine, distinct-item `transferred` observations still correctly climb the score and flip status to `'provisional'` — so legitimate multi-observation progression was not broken by the fix. `npx tsc --noEmit` clean; `npm run test:assessor` (unaffected code path) still passes; `npm run test:live` fails identically on the ORIGINAL unmodified code in this environment (confirmed via `git stash`) — a pre-existing sandbox/network limitation (no reachable Gemini Live endpoint here), not a regression.
**Generalized rule:** whenever a system computes two different signals that both claim to represent "how well does this learner know X" (a continuous score AND a categorical status), fix disagreements AT THE SOURCE that computes the continuous one, not by gating each consumer separately — there will always be another consumer (a prompt, a new UI, an API route) you didn't think to gate. Reuse an existing, already-validated evidence-sufficiency rule before inventing a new tunable constant.

### #4 — 2026-09-26 — Mid-session plan-delta guidance (`compilePlanDelta`) never reached the live tutor at all
**Files:** `server.ts` (WS connection handler — `compilePlanDelta` call site, `sendToolResponse()`). **Symptom:** found while implementing T19 (docs/BUILD_PLAN.md's guidance-injection spike). An earlier audit had claimed "dynamic plan-delta injection already works end-to-end via a different mechanism." Re-verified this myself by grepping every `sendClientContent`/`liveSession.` call site and found the claim was wrong: `delta.instruction` from `compilePlanDelta()` -- which carries PARK_AND_ESCALATE's "park this concept, tell the learner you'll return to it" guidance, `encourageReset`'s pacing guidance, and representation-switch instructions -- was sent ONLY to the browser, as a `plan_update` WS message for the Tutor's-Reasoning debug panel. It was never passed to `liveSession.sendToolResponse(...)` or `sendClientContent(...)`, so the live Gemini model itself never received it. The only guidance that DID reach the model was a narrower, separately-computed value (`assessment.tutorGuidance`, from the per-turn diagnostician), via the existing `sendToolResponse(call, { instruction: assessment.tutorGuidance })` call. Net effect: if a retry cap was hit and the plan compiler decided to park a concept, the *browser* would show that decision in the debug panel, but the *tutor's voice* would carry on as if nothing had changed -- the single most safety-relevant persona move (PARK_AND_ESCALATE) was silently never delivered to the model.
**Fix:** added a `pendingPlanGuidance` (+ `pendingPlanGuidanceQueuedAt` for latency logging) module-level variable in the WS connection closure. `compilePlanDelta`'s call site sets it whenever `delta.instruction` is truthy, in addition to (not instead of) the existing browser `plan_update` push. The shared `sendToolResponse()` function -- the single funnel every tool call already goes through -- merges any pending guidance into the *next* outgoing tool response's `instruction` field (concatenated with, not overwriting, that call's own instruction text), logs `[T19 guidance-injection]` with the queued-to-delivered latency, and clears the pending value. Zero new live-session API surface; zero risk of interrupting tutor speech, since it rides a response that was already about to be sent for an unrelated reason.
**Why not `sendClientContent()` (TECHNICAL_SPEC.md §5.3 Option A):** that option is explicitly conditioned on "only when the model is not speaking" -- the code has no reliable way to detect that from this side of the Live API, and this sandbox cannot reach a live Gemini Live endpoint at all (`npm run test:live` -> `ECONNREFUSED 127.0.0.1:3999`, confirmed identical on unmodified code via `git stash`), so a new, untested injection path could not be validated before shipping. Piggybacking on `sendToolResponse` reuses a call path that is already exercised by every existing tool call and already known to work.
**Trade-off / known limitation:** delivery is not instant -- the guidance waits for whatever tool call happens to fire next (in practice `assess_child_reasoning` fires on nearly every turn, so the wait is normally at most one turn, but there is no hard upper bound if the model goes several turns without calling any tool). Formal p50/p95 added-latency numbers (T19's acceptance criterion) cannot be produced from this sandbox -- see the `[T19 latency]` log line added in `server.ts` and `DECISIONS.md` entry `D-2026-09-26-4` for how to capture them on a machine with real Gemini Live access.
**Generalized rule:** a value computed once and then "sent" is not necessarily sent everywhere it needs to go -- when a compiler/decision function's output has more than one consumer (here: browser debug panel AND live model), grep every actual delivery call site (not just where the value is *read*) before trusting a claim that it "already reaches" a destination. Don't take a prior audit's characterization of a data-flow claim at face value when it's cheap to re-verify with a grep.

### #5 — 2026-09-26 — T14 built: Profiler + Claim Validator, and why confidence must never come from the LLM
**Files:** `src/adaptive/profiler.ts` (new), `src/adaptive/claimValidator.ts` (new), `src/adaptive/repo/{types,file,firestore}.ts` (added `sessionId` to `EventFilter`), `server.ts` (wired into the live-voice WS `close` handler). **Context, not a bug:** this is the first landmine entry for a NEW capability rather than a fix, recorded because the design choice matters for anyone extending it. docs/LEARNER_MODEL.md §5.2 calls the Profiler "Gemini, stronger model, JSON schema" and the Claim validator "deterministic" — the two words together are easy to blur if you let the Profiler's JSON response include a confidence number "because the model already estimated one anyway." Don't: `ProposedClaim` (the Profiler's output shape) has NO confidence field on purpose. §6.3 gives an exact formula (`cap(n)` by evidence count, `n` = distinct evidenceRefs) and confidence is computed ONLY in `claimValidator.ts`'s `capForEvidenceCount()`. If a future change adds an LLM-supplied confidence and starts blending it in, the validator stops being deterministic and the whole point of separating "propose" from "validate" (LLMs hallucinate scope, evidence, and certainty; a fixed formula cannot) is lost.
**Also note:** the Profiler is deliberately NOT wired into the legacy `POST /api/session/:sessionId/end` route (the quiz-click path) — only the live-voice WS `close` handler, because that is the actual "session end" this project's core loop cares about. If the quiz-click path is ever revived as a first-class flow, it needs its own explicit decision about whether/how to call `runProfiler`, not a silent copy-paste.
**Generalized rule:** when a spec calls one stage "LLM" and the next stage "deterministic," treat that boundary as load-bearing — any value that crosses it in the wrong direction (a judgment score leaking from the LLM stage into what's supposed to be a fixed-formula gate) quietly reintroduces exactly the failure mode the deterministic stage was built to prevent. Grep for where a value ORIGINATES, not just where it's read, before assuming a "deterministic" component is still deterministic.

### #6 — 2026-09-26 — One logical key, several spellings: learner history silently split across keys
**Files:** `src/curriculum/catalog.ts` (`conceptTypeFor`), `src/adaptive/reasoningAssessor.ts` (`misconceptionCatalog`), `src/curriculum/structure.ts`, `scripts/seed-demo-learners.ts`, `server.ts`. **Symptoms (found in a syllabus review, D-2026-09-26-7):** (1) `conceptType` — the key for the cross-concept strategy profile, the plan's R-WATCH sibling rule and Profiler claim scope — was written as the chapter title by live sessions (`conceptDef.chapter`) but as `"geometry"` by the seed script, so a seeded learner's "visual diagrams helped last time" history was invisible to their next live session. (2) Misconception ids were positional (`<conceptId>::m1`) in the live diagnostician but hand-named (`ssa-congruence`) in the seed, so a live repeat of a seeded, confirmed misconception opened a SECOND ledger entry instead of adding an observation. (3) Concept ids embedded the upload's file name, so re-uploading the same book under another name would have orphaned every learner's history. **Fix:** ids and types are assigned once at ingest and never changed (`finaliseCourse` keeps published concepts verbatim; `applyStructure` keeps published types); every writer and reader of `conceptType` calls `conceptTypeFor(def, state)`; the catalogue uses the stable `misconceptionDetails[].id`; the seed script takes ids from `misconceptionCatalog()` of a real course.
**Generalized rule:** when a value is used as a KEY for longitudinal data (history, ledgers, profiles), there must be exactly one function that produces it, and every writer — including scripts and fixtures — must call it. Grep for every place the key is *written*, not just read. Never derive a durable key from something incidental (a file name, list position).

### #7 — 2026-09-26 — Logic that was "working" only because its input was always empty
**Files:** `src/plan/compile.ts` (R-PREREQ-FIRST, R-PROBE, R-FAST), `src/components/SubjectSelector.tsx` (unlock rule). **Symptom:** with every course's prerequisite graph empty, three plan rules never ran, so nobody noticed that (a) an UNEVIDENCED prerequisite counted as weak (`pKnown ?? 0 < 0.6`) — once real graphs existed every new learner would be redirected away from the concept they clicked; (b) R-PROBE's check question came from the prerequisite's own first prerequisite (a question about the wrong idea); (c) the subject list would lock most of a course. **Fix:** D-2026-09-26-8 — evidence-gated R-PREREQ-FIRST, probe-first for unevidenced prerequisites, check question from the target's link, "Builds on" hints instead of locks; covered by `tests/smoke/curriculum-ingest.mjs`.
**Generalized rule:** when you start populating data that used to be empty (a graph, a list, an optional field), re-audit every consumer of it as if it were new code — "it has always worked" meant "it has never run".

### #8 — 2026-09-28 — Node `fetch('http://localhost:PORT')` can hang indefinitely against a server bound to `0.0.0.0`
**Files:** `tests/smoke/tutor-turn.mjs` (new, T08's test). **Symptom:** while writing the first HTTP-level smoke test that actually starts `server.ts` and hits it with `fetch` (every earlier test either stubs `@google/genai` and never touches HTTP, or is a manual `curl`), the server logged `[Server] AI Tutor backend running on http://localhost:PORT` — genuinely up and accepting connections, confirmed separately with `curl` — but the test script's own `fetch('http://localhost:PORT/api/health')` inside a polling loop never succeeded, timing out every time with no thrown error visible (caught by the loop's own try/catch, which is what made it silent instead of an obvious crash).
**Cause:** `server.listen(PORT, '0.0.0.0', ...)` binds only the IPv4 wildcard. Node's built-in `fetch` (undici) can resolve the hostname `localhost` to the IPv6 loopback `::1` first on some hosts (Happy Eyeballs / getaddrinfo ordering) — a connection to `::1:PORT` is refused (nothing is listening there), and depending on the environment that refusal can retry/hang rather than fail fast, burning the whole timeout budget before the loop gives up.
**Fix:** use `http://127.0.0.1:PORT` (an explicit IPv4 literal), never `http://localhost:PORT`, in any test that starts a real server here and hits it with `fetch`. Confirmed this alone was the entire fix — no other change was needed once the literal was pinned.
**Generalized rule:** when a Node script's own `fetch` against a server you just started appears to hang or silently time out, and `curl` against the exact same URL from a shell works fine, suspect `localhost`'s IPv4-vs-IPv6 resolution before suspecting the server, the port, or a race condition — pin the loopback address literally and re-test before debugging anything else.

### #9 — 2026-09-28 — `device_commit_files` can report success before the write is actually visible to `device_bash`
**Files:** none (tooling behavior, not a code bug) — hit while committing the fixes for #10 below.
**Symptom:** edited a file locally, staged it, called the device-commit tool, got back `{"written": [...], "rejected": []}` — genuine success — then immediately `wc -c`/`grep`'d the same file over `device_bash` and saw the OLD content/byte count, as if the edit had never landed. Re-running the exact same commit call a few seconds later then showed the new content correctly.
**Cause:** apparent propagation lag between the commit call returning and the write being visible on the path `device_bash` reads through (different underlying view of the same connected folder). Not consistent — sometimes immediate, sometimes needed a retry.
**Fix:** after any commit you're about to immediately depend on (e.g. running a test against the file you just fixed), verify with a cheap read (`wc -c`, or `grep` for a string you know you just added) before trusting it; if the byte count/content still matches the OLD version, retry the same `device_commit_files` call once (a short `sleep` was NOT enough — the retry itself is what worked) rather than assuming your edit failed and re-diagnosing a phantom bug.
**Generalized rule:** never chain "commit a fix" → "immediately run a test that depends on it" without a verification read in between when working through the device bridge — a stale-read false negative here looks exactly like the fix not working, and re-investigating the (already-correct) code instead of the propagation lag wastes real time.

### #10 — 2026-09-28 — A diagnostician classification with no matching catalogued misconception id silently degraded to "everything's fine"
**Files:** `server/routes/tutor.ts`, `server.ts` (both had the identical bug — see docs/DECISIONS.md D-2026-09-28-4 for full detail).
**Symptom:** `compilePlanDelta`'s `outcome` was computed as `candidateMisconceptions.length > 0 ? (…) : (classification === 'wrong_answer' || 'needs_clarification' ? 'failed_check' : 'sound')`. The diagnostician's own `classification` enum includes `misconception_behind_correct` (the project's own first-class case — a correct-looking answer with wrong reasoning) as a value distinct from `wrong_answer`/`needs_clarification`, and its `candidateMisconceptionIds` are filtered down to only ids present in that concept's catalogue (`reasoningAssessor.ts`). A real diagnosis of `misconception_behind_correct` with no catalogued id matched — an expected, not edge, case — fell through both branches to `'sound'`, and the tutor was told to "continue teaching" exactly when it should have probed.
**Cause:** the `outcome` derivation only branched on `candidateMisconceptions.length`, never on `classification` itself for this one value — an omission, not a typo, so nothing about the code "looked wrong" on a read-through; it only surfaced by scripting the exact input combination (classification set, candidate ids empty) in `tests/smoke/tutor-turn-offline.mjs` and asserting on the resulting `outcome`.
**Fix:** `assessment.classification === 'misconception_behind_correct'` now maps to `'misconception_suspected'` on its own, before falling back to the wrong_answer/needs_clarification/sound branch.
**Generalized rule:** when an enum used for branching has a value that means "detected but not yet categorised" (here: a real signal without a catalogued id to hang it on), check every place that branches on a *subset* of that enum's values (`candidateMisconceptions.length`, here) for whether the "detected but uncategorised" case was actually covered, or just fell through the gap between two other conditions that were each individually reasonable.

### #11 — 2026-09-28 — `npm run test` had never actually been run to completion in this environment; two of its own pieces were broken
**Files:** `tests/live/genai-live-stub.mjs`, `tests/live/run.mjs` (see docs/DECISIONS.md D-2026-09-28-5 for full detail).
**Symptom:** after adding a new test to the main `npm run test` aggregate (to close out #10 above with a permanent regression guard), running the aggregate failed — not the new test, but the existing `tests/live/run.mjs` — first with an esbuild error (`No matching export ... for import "createPartFromFunctionResponse"`), and after fixing that, with the server appearing to hang forever (spawned, visibly consuming CPU, never printing a single line of output, never answering `/api/health`) within the 6-second budget the test gave it.
**Cause:** two separate, unrelated bugs. (1) `server.ts` started importing `createPartFromFunctionResponse` from `@google/genai` the moment T08 wired `registerTutorRoutes(app)` in, days before this — `tests/live/genai-live-stub.mjs` (the fake `@google/genai` this test bundles against) was never updated to export it, so the build broke as soon as anything actually tried to bundle `server.ts` against this stub, which nothing had since. (2) The server was never actually hung — it took ~19 seconds to finish starting on this network-mounted filesystem (confirmed by temporarily instrumenting startup with trace `console.error` calls and re-timing), and the test's own health-check loop only waited 6 seconds (40 × 150ms) before giving up — the *exact same* budget-too-short mistake landmine #8 already fixed once in `tests/smoke/tutor-turn.mjs`, just never carried over to this older file, plus that file *also* still had landmine #8's `localhost`-vs-`127.0.0.1` bug.
**Fix:** added the missing export to the live stub. Bumped `tests/live/run.mjs`'s health-check budget to 400 × 150ms = 60s (matching `tutor-turn.mjs`'s own precedent) and switched `localhost` to the `127.0.0.1` literal.
**Generalized rule:** a test that hasn't been run in a while can accumulate more than one independent bug, and each one masks whether the others exist — don't stop investigating at the first error and assume fixing it will reveal a passing test; rebuild and rerun after each individual fix, because the next failure may be a completely different bug, not a symptom of the one you just fixed. Also: an aggregate test command (`npm run test`) that fails to even *build* is worse than having no test at all, because nobody re-runs a command they've stopped trusting — treat a build failure in ANY step of an aggregate as equally urgent as a failing assertion, not as a lesser problem.

### #12 — 2026-09-28 — Fixing a test's infrastructure can unmask a stale "golden snapshot" the infrastructure bug had been hiding
**Files:** `tests/live/run.mjs` (see docs/DECISIONS.md D-2026-09-28-5; not fixed, flagged for priority).
**Symptom:** once #11 above was fixed and `tests/live/run.mjs` could finally run to completion, it failed 7 of its own assertions — including a literal regex check for the prompt text `/^You are "Dr\. Marcus Vance"/`, a persona name that does not appear anywhere in the current, actively-developed persona system (`src/persona/compose.ts`).
**Cause (most likely, not fully confirmed):** this file compares live output against a baseline ("the original build") that was written once and never updated as the persona/tool/observer systems were deliberately changed since — i.e. the test had been silently broken (via #11's build error) for long enough that nobody noticed the baseline itself had also gone stale underneath it.
**Why this was NOT fixed in the same pass:** two of the seven failures are numeric/behavioural, not text matches (`understanding moves at most 20 per exchange (model said 90, shown 0)`, and misconception-status/concept-field checks on `src/adaptive/liveObserver.ts`'s output) — these could be a real bug in the observer, not just a stale expectation, and there is no way to tell which without a dedicated investigation of that subsystem. Rewriting the assertions to match current output, without knowing that, risks quietly deleting evidence of a real regression rather than fixing or reporting it.
**Generalized rule:** when fixing a test's plumbing (a build error, a timeout, a wrong URL) finally lets it run and it THEN fails on its actual assertions, do not assume those new failures are "just more infrastructure to fix" or silently update the expected values to match current output — a golden-snapshot test that couldn't run for a long time may be failing for a completely different, substantive reason once it can. Report it as a distinct finding and let whoever owns that subsystem decide, rather than resolving the ambiguity yourself by picking whichever fix makes the test green.

### #13 — 2026-09-28 — Firestore rejects nested arrays, and board pictures are full of them
**Files:** `src/curriculum/pregenStore.ts` (`toFirestore` / `fromFirestore`), `tests/smoke/board-visual.mjs` (see D-2026-09-28-7).
**Symptom:** a board picture is naturally nested arrays — a polygon's `points: [[0,0],[3,0],[3,4]]`, a table's `rows: [["x","y"],["1","3"]]`, a step's `show: [...]` inside `steps: [...]`. The local JSON store saves these without complaint, so everything works in development; the first Firestore write of the same record fails with "Nested arrays are not supported" and the whole pregen record (lesson text included) is lost.
**Fix:** pictures are stored as ONE string field, `visualsJson`, encoded in `toFirestore` and decoded in `fromFirestore`; `lessonData.visual` / `lessonData.visual3d` are stripped before saving (the server attaches them at read time from `visuals`). A smoke test round-trips a picture with polygon points and table rows through both functions and asserts no array anywhere in the Firestore shape contains another array.
**Generalized rule:** the local JSON store is more permissive than Firestore. Any new stored field whose shape can contain an array of arrays must go through `toFirestore`, and must have a round-trip test — passing locally proves nothing about production storage.

### #14 — 2026-09-28 — An SVG glow filter hid perfectly valid vertical and horizontal lines; tests passed on markup that looked wrong
**Files:** `src/components/BoardVisualView.tsx` (the focus glow `<filter>`), `tests/smoke/board-visual-render.mjs`.
**Symptom:** when the tutor put a vertical line like `x = 3` (or any horizontal line) "in focus", it vanished from the board. Every render test passed, because the `<line>` element was present in the markup with correct coordinates — only a real browser screenshot showed the empty space.
**Cause:** an SVG `<filter>` defaults to `filterUnits="objectBoundingBox"`, so its region is a percentage of the element's bounding box. A perfectly vertical or horizontal line has a bounding box of zero width or height, so the filter region is zero and the browser paints nothing.
**Fix:** the filter uses `filterUnits="userSpaceOnUse"` with a region covering the whole 1000×600 board. A regression test asserts the filter declares user-space units, so the bounding-box default cannot silently come back.
**Generalized rule:** for anything a child SEES, a markup-level test is not enough — check a real rendered screenshot (Playwright + the pre-installed Chromium; see `scripts/preview-visuals.tsx`) before calling a visual change done. Then turn whatever the screenshot caught into a markup assertion so it stays fixed.

### #15 — 2026-09-30 — A critic call that fails must never count as a pass
**Files:** `src/quality/critic.ts`, `src/curriculum/lessonGen.ts`, `photoGen.ts`. **Risk:** when the reviewing model is unreachable or returns junk, "no issues found" is indistinguishable from "did not look". **Rule:** a failed critic is recorded as `criticRan:false`; photos are not shipped when the reviewer is unreachable; the scorecard prints `critic: no` and never treats lint-clean as reviewed. Any new gate must distinguish *checked and clean* from *not checked*.

### #16 — 2026-09-30 — The local store accepts data Firestore rejects
**Files:** `src/curriculum/pregenStore.ts`. Nested arrays are rejected by Firestore (see #13); pictures and the quarantine map therefore travel as JSON string fields (`visualsJson`, `quarantineJson`) and are decoded on read. A change that works against the local JSON store can still fail in production — round-trip any new field through the Firestore encode/decode path (`serve.mjs`/store tests) before trusting it.

### #17 — 2026-09-30 — Shell hazards on the linked device
`pkill -f server.ts` kills the tool shell itself (exit 143) — stop servers by PID. Heredocs above ~26 KB fail with E2BIG — write files in pieces. The connected folder forbids deletes (move to `_to_delete/`). `tests/live/run.mjs` has 7 failures that pre-date the quality work (landmine #12); `npm test` therefore still fails — use `npm run verify` for the quality gates.

### #18 — 2026-09-30 — Unbounded repair loops and `--force` overwriting good records burned real tokens
**Files:** `src/visual/generate.ts`, `src/curriculum/lessonGen.ts`, `scripts/pregenerate-assets.ts`, `src/quality/leakLint.ts`. A gate that the model cannot satisfy (a lint stricter than the prompt, a fragment matching a multi-part answer) costs 3 repair rounds + critics per artefact, then withholds it. Rules: (1) every lint must be satisfiable from what the generation prompt says — tell the model the constraint up front; (2) repair only on errors, stop when the same error codes repeat; (3) a regeneration must never replace a stored artefact with a worse one; (4) every paid call type (text, critic, **image**) must be counted and cappable (`--max-calls`, `--max-images`); (5) before a long run, print the plan with `npm run pregen:ch1:plan`. **Superseded by D-2026-09-30-6:** generation is single-shot — one call per artefact from a complete contract, one review per concept, no in-loop critic or repair (`--repair N` is opt-in). Do not reintroduce generate→critic→repair loops.

## 3. The doc-sync rule (how this stays honest)

Every commit that touches a file in the left column of §1's table should touch the doc(s) in the corresponding right column in the SAME commit — not "later." This is enforced (as a warning, not a hard block, given hackathon time pressure) by `scripts/check-docs-sync.mjs`, wired to `npm run check:docs` and to a pre-commit hook at `.githooks/pre-commit` (enabled via `git config core.hooksPath .githooks`, already set in this repo — see `docs/ARCHITECTURE.md`). If the hook warns you and you deliberately want to skip updating docs (e.g. a pure typo fix), that's fine — it's advisory, not blocking — but a **new landmine, a new architectural decision, or a change to what a tool/route/persona does** should never be skipped.

If you are an AI agent and you just fixed a bug or changed a design decision: add a landmine entry (§2) or a `DECISIONS.md` entry BEFORE you consider the task done. This file existing and being stale is worse than it not existing.
