// ─────────────────────────────────────────────────────────────────
// Generate guided (line-by-line chalkboard) lessons with Gemini.
//
//   npm run guided:first-chapter            first chapter of every subject
//   npx tsx scripts/generate-guided.ts --concepts <id>,<id>
//   npx tsx scripts/generate-guided.ts --subject igcse--g8--biology --chapter "^Chapter 1:"
//
// Options:
//   --preset first-chapter   per subject: chapterNumber 1, or (no chapter numbers) the first 3 in teaching order
//   --subject <id>           only this subject
//   --chapter <regex>        only concepts whose chapter matches
//   --concepts a,b           exactly these concept ids
//   --force                  regenerate even if a generated lesson exists
//   --no-critic              skip the independent critic (not recommended)
//   --attempts N             draft + repairs per concept (default 3)
//   --dry-run                list what would be generated, call nothing
//
// Output:
//   src/guided/generated/<conceptId>.json    lessons that passed every check (served, bundled into the build)
//   src/guided/generated/index.ts            rewritten to list them
//   data/guided/withheld/<conceptId>.json    lessons that did not pass, with the reasons (NOT served)
//   data/guided/report-<time>.json           what happened, per concept
// A concept whose lesson is withheld keeps the standard tutor.
// ─────────────────────────────────────────────────────────────────

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { initFirebaseAdmin } from '../src/firebase/admin';
import { getPregenAsync } from '../src/curriculum/pregenStore';
import { gatewayModel } from '../src/quality/model';
import { gatewayStats, setGatewayLogSink } from '../src/ai/gateway';
import { generateGuidedLesson, sourceFromCurriculum, QuotaExhaustedError } from '../src/guided/generate';

dotenv.config();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const GEN_DIR = path.join(ROOT, 'src', 'guided', 'generated');
const WITHHELD_DIR = path.join(ROOT, 'data', 'guided', 'withheld');
const REPORT_DIR = path.join(ROOT, 'data', 'guided');

const argv = process.argv.slice(2);
const flag = (n: string) => argv.includes(n);
const argVal = (n: string) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : undefined; };

/** Rewrite src/guided/generated/index.ts so every generated lesson is bundled (server build and Docker image). */
export function writeGeneratedIndex(dir = GEN_DIR): number {
  const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort() : [];
  const lines = [
    '// AUTO-GENERATED by scripts/generate-guided.ts - do not edit by hand.',
    '// Each file is a guided lesson written by Gemini that passed the checks (validate.ts) and the critic.',
    "import type { GuidedScript } from '../types';",
    ...files.map((f, i) => `import g${i} from './${f}';`),
    '',
    `export const GENERATED_GUIDED_SCRIPTS: GuidedScript[] = [${files.map((_, i) => `g${i}`).join(', ')}] as unknown as GuidedScript[];`,
    '',
  ];
  fs.writeFileSync(path.join(dir, 'index.ts'), lines.join('\n'));
  return files.length;
}

function selectConcepts(curricula: any[]): Array<{ concept: any; course: any }> {
  const only = argVal('--concepts')?.split(',').map((x) => x.trim()).filter(Boolean);
  const subject = argVal('--subject');
  const chapter = argVal('--chapter') ? new RegExp(argVal('--chapter')!) : null;
  const preset = argVal('--preset');
  const out: Array<{ concept: any; course: any }> = [];
  for (const course of curricula) {
    if (subject && course.id !== subject) continue;
    let concepts: any[] = [...(course.concepts ?? [])];
    if (only) concepts = concepts.filter((c) => only.includes(c.id));
    if (chapter) concepts = concepts.filter((c) => chapter.test(String(c.chapter ?? '')));
    if (preset === 'first-chapter') {
      const numbered = concepts.filter((c) => typeof c.chapterNumber === 'number');
      concepts = numbered.length
        ? numbered.filter((c) => c.chapterNumber === Math.min(...numbered.map((x) => x.chapterNumber)))
        : concepts.sort((a, b) => (a.typicalTeachingOrder ?? 999) - (b.typicalTeachingOrder ?? 999)).slice(0, 3);
    }
    concepts.sort((a, b) => (a.typicalTeachingOrder ?? 999) - (b.typicalTeachingOrder ?? 999));
    out.push(...concepts.map((concept) => ({ concept, course })));
  }
  return out;
}

async function main() {
  const curricula: any[] = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'curricula.json'), 'utf8'));
  const labelOf = new Map<string, string>(curricula.flatMap((c) => (c.concepts ?? []).map((x: any) => [x.id, x.label])));
  const picked = selectConcepts(curricula);
  if (!picked.length) { console.error('Nothing selected. Use --preset first-chapter, --subject, --chapter or --concepts.'); process.exit(1); }

  console.log(`\nGuided lessons to generate: ${picked.length}`);
  for (const { concept, course } of picked) {
    const exists = fs.existsSync(path.join(GEN_DIR, `${concept.id}.json`));
    console.log(`  ${exists && !flag('--force') ? '= keep  ' : '+ write '} ${course.label} ${course.grade ?? ''} | ${concept.chapter ?? ''} | ${concept.label}`);
  }
  if (flag('--dry-run')) return;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) { console.error('GEMINI_API_KEY not set.'); process.exit(1); }
  try { initFirebaseAdmin(); } catch { /* local files only */ }
  fs.mkdirSync(GEN_DIR, { recursive: true });
  fs.mkdirSync(WITHHELD_DIR, { recursive: true });
  const model = gatewayModel(apiKey, 2, 180_000);
  const attempts = Number(argVal('--attempts') || 4);
  // Every model call goes to a log file as well, so a run can be checked afterwards.
  const runStamp = new Date().toISOString().replace(/[:.]/g, '-');
  const runLog = path.join(REPORT_DIR, `run-${runStamp}.log`);
  fs.mkdirSync(REPORT_DIR, { recursive: true });
  const failures = new Map<string, number>();
  setGatewayLogSink((e) => {
    const line = `${new Date().toISOString()} [gateway] ${e.call} role=${e.role} model=${e.model} ok=${e.ok} ms=${e.ms}${e.outputChars ? ` chars=${e.outputChars}` : ''}${e.usedFallback ? ' FALLBACK' : ''}${e.error ? ' err=' + e.error.slice(0, 300) : ''}`;
    fs.appendFileSync(runLog, line + '\n');
    if (!e.ok) {
      const kind = /deadline/i.test(e.error || '') ? 'timeout' : /could not parse JSON/i.test(e.error || '') ? 'bad JSON' : /\b(429|503)\b|high demand|unavailable|rate/i.test(e.error || '') ? 'busy (429/503)' : (e.error || 'error').slice(0, 60);
      const k = `${e.model}: ${kind}`;
      failures.set(k, (failures.get(k) ?? 0) + 1);
    }
  });
  const logConcept = (msg: string) => fs.appendFileSync(runLog, `${new Date().toISOString()} ${msg}\n`);
  const report: any[] = [];

  for (const { concept, course } of picked) {
    const target = path.join(GEN_DIR, `${concept.id}.json`);
    if (fs.existsSync(target) && !flag('--force')) { report.push({ conceptId: concept.id, result: 'kept' }); continue; }
    const t0 = Date.now();
    const record = await getPregenAsync([concept.id]);
    if (!record) console.warn(`  ! ${concept.label}: no stored record - generating without pictures`);
    const { source, pictures, pictureRefs } = sourceFromCurriculum(concept, course, record, (id) => labelOf.get(id) || id);
    process.stdout.write(`  … ${concept.label} `);
    logConcept(`=== ${concept.id}`);
    let r: Awaited<ReturnType<typeof generateGuidedLesson>>;
    try {
      r = await generateGuidedLesson(source, pictures, pictureRefs, model, { maxAttempts: attempts, critic: !flag('--no-critic') });
    } catch (err) {
      if (!(err instanceof QuotaExhaustedError)) throw err;
      console.log('\n\nSTOPPED: every Gemini model is out of credits or daily quota.');
      console.log('  Free-tier quotas reset daily (see AI Studio > Rate limits); prepaid credits need a top-up at https://ai.studio/projects.');
      console.log('  Nothing was marked as failed. Lessons already written are kept. Run the same command again later: finished lessons are skipped.');
      report.push({ conceptId: concept.id, label: concept.label, result: 'stopped-no-quota' });
      break;
    }
    const secs = ((Date.now() - t0) / 1000).toFixed(0);
    if (r.script) {
      const lines = r.script.beats.reduce((n, b) => n + (b.lines?.length ?? 0), 0);
      const asks = r.script.beats.reduce((n, b) => n + (b.lines?.filter((l) => l.ask).length ?? 0), 0);
      const out = { ...r.script, meta: { source: 'gemini', model: r.model, generatedAt: new Date().toISOString(), attempts: r.attempts, criticCalls: r.criticCalls, warnings: r.warnings } };
      fs.writeFileSync(target, JSON.stringify(out, null, 2) + '\n');
      const stale = path.join(WITHHELD_DIR, `${concept.id}.json`);
      if (fs.existsSync(stale)) fs.writeFileSync(stale, JSON.stringify({ supersededBy: 'src/guided/generated', at: new Date().toISOString() }) + '\n');
      console.log(`✓ ${r.script.beats.length} beats, ${lines} lines, ${asks} questions (${r.attempts} draft${r.attempts === 1 ? '' : 's'}, ${secs}s)${r.warnings.length ? `, ${r.warnings.length} warning(s)` : ''}`);
      report.push({ conceptId: concept.id, label: concept.label, result: 'ok', model: r.model, beats: r.script.beats.length, lines, asks, attempts: r.attempts, warnings: r.warnings });
    } else {
      fs.writeFileSync(path.join(WITHHELD_DIR, `${concept.id}.json`), JSON.stringify({ conceptId: concept.id, label: concept.label, model: r.model, errors: r.errors, warnings: r.warnings, lastDraft: r.quarantined ?? null }, null, 2) + '\n');
      console.log(`✗ WITHHELD after ${r.attempts} draft(s), ${secs}s - ${r.errors.slice(0, 2).join(' | ').slice(0, 240)}`);
      report.push({ conceptId: concept.id, label: concept.label, result: 'withheld', model: r.model, attempts: r.attempts, errors: r.errors });
      logConcept(`withheld: ${r.errors.join(' | ')}`);
    }
  }

  const n = writeGeneratedIndex();
  const reportPath = path.join(REPORT_DIR, `report-${new Date().toISOString().replace(/[:.]/g, '-')}.json`);
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  const st = gatewayStats();
  const ok = report.filter((r) => r.result === 'ok').length, held = report.filter((r) => r.result === 'withheld').length;
  console.log(`\nDone: ${ok} written, ${held} withheld, ${report.length - ok - held} kept. ${n} generated lesson(s) are now served.`);
  console.log(`Model calls: ${st.calls} (${st.failed} failed). Report: ${path.relative(ROOT, reportPath)}  Log: ${path.relative(ROOT, runLog)}`);
  if (failures.size) console.log('Failed calls by cause: ' + [...failures].sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ×${v}`).join('; '));
  if (held) console.log('Withheld lessons (with reasons) are in data/guided/withheld/ - those concepts keep the standard tutor.');
  console.log('Restart the server to serve the new lessons.\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => { console.error(err); process.exit(1); });
}
